Documentation Guidelines
========================
Nilay Binjola <nilaybinjola@gmail.com>
22 June 2014
:Author Initials: NB
:toc:
:icons:
:numbered:

== Introduction
The project was made open-source as of January, 2014 with a Git repository hosted on Github. The project is free for users, hackers, maintainers, administrators etc. to review, use and modify. Hence, the project requires proper formal documentation. This document contains general guidelines to be followed while documenting installation, configuration, modules, features etc.

== Directory Structure
Documentation has a complete subheirarchy as shown below. "/" refers to the repository primary heirarchy root. The following table lists directories and some important subdirectories along with their descriptions.
[align="center",cols="^1,3",options="header"]
|===========================
|Directory		^e|Description
|/Documentation		|Documentation heirarchy root and root directory of the entire documentation system heirarchy. Contains documentation compilation script and HTML documents with the documentation index HTML page. Also contains the documentation landing page.
|/Documentation/AsciiDoc|Contains documentation AsciiDocs in human-readable plain-text format. They form the source of the documentation.
|/Documentation/images	|Contains images for the documentation HTML pages and the documentation index HTML page.
|===========================

== Documentation Structure
All documentation as of 27^th^ January 2014 is to be made a part of the '/Documentation' subheirarchy. Documentation is made using *AsciiDoc* which is a human-readable document format using plain-text mark-up conventions. These '.asciidoc' files act as source files for document generation. The documentation structure has a documentation compilation script that compiles the AsciiDocs to formatted HTML pages in the documentation root. All images are stored in '/Documentation/images' and paths in the AsciiDocs must be made accordingly as HTML pages are kept in the documentation root.

Documentation starts from the 'index.html' landing page. This stand-alone page contains external links relevant to the project. Also, the page contains an _About_ section and a _Credits_ section. Credits are sorted name-wise aplhabetically and contain _name, email, role in project and snail-mail address_. Documentation pages are indexed in the *Documentation Index* which has a brief introduction of the project along with links to all documentation pages.

== Creating a Page

=== Search and Improve. Don't duplicate.
You should first search what you are looking for before diving into writing a page. This will save you time and the documentation maintainer some headache. If you find what you are looking for but find it lacking certain elements, it is recommended that instead of creating a new page you improve it. You can search for the page you are looking for in the *Documentation Index* page.

=== Create a Page
Create a page as a AsciiDoc document in the '/Documentation/AsciiDoc' subdirectory while adhering to the guidelines below. Choose a proper name. Follow modularity rules and keep the style similar to that of a wiki. Align the style to that of existing pages. Provide all applicable sections in the page.

=== Update 'doc-index.asciidoc'
After creating a page, you should update the 'doc-index.asciidoc' document by adding an entry in the *Contents* section along with a working relative link. All links are relative. You should also add a small 1 line description aligning with previously done entries.

=== Compile Pages
Now, you must compile the AsciiDocs to HTML format for easy viewing. Use the '/Documentation/MakeFile.sh' compilation script. It will compile all AsciiDoc pages including yours and 'doc-index.asciidoc' to HTML documents in the documentation root directory.

== Documentation Guidelines

=== General Guidelines
Some general guidelines to be followed on all pages and all sections are:

* *Comprehensive* - Describe all the functionality of the product you can. Anything and everything that is relevant.
* *Conformant* - Describe actual behavior and observations and not what is expected.
* *Clarity* - Be clear. Use short and effective sentences.
* *Consistent* - Be consistent with vocabulary and terminologies. Use proper AsciiDoc formatting.
* *Modularity* - Divide the documentation page into modules/sections.
* *Text Formatting* - Format text wherever needed using appropriate styles like bold, italics, underline etc. in AsciiDocs.

It is therefore recommended that you understand *AsciiDoc* usage properly before starting off here. It is extremely easy and powerful and is used by extensively by the industry.

=== Page Guidelines
Divide the page into sections and modules that are properly named. This allows for better readability. AsciiDoc will automatically create the table of contents. Some guidelines/rules for creating pages are:

==== Page Title
Page title should use capitalization and spaces between words. It should align to the standard vocabulary and terminology used in the rest of the documentation. Long page titles should be avoided.

==== Page Metadata
All pages should at least contain the following metadata:

. Author's complete name
. Author's active email address
. Date of creation of document
. Author's initials

==== Table of contents
For easy referencing and readability, a table of contents must always be included on top. The table of contents should have icons and numbers enabled. It should at least have sections listed with a depth of 2.

==== Sections
A page should be divided into sections. This will give proper structure to the page and will enable abstractions to be made as the documentation is for users, hackers and maintainers alike. Some sections common to most pages and their guidelines are:

===== Introduction
A short and concise section describing the use and objective of the module/script/page. Should be to-the-point. Preferably 1 or 2 sentences.

===== Installation
A short and concise section that describes the steps needed to install the module/script etc. Should include the dependency tree if required. Installation should start from integrating the module in the project to enabling or launching it. It may also contain files that can be used to customize the module. Links to downloads and installation notes of dependency tree software should be listed in the *External Links* section.

===== Usage
This section deals with how the end-user will use the module/script etc. Should contain commands to be issued and their purposes. Should also contain the person to be approached in case something goes wrong for the end-user.

===== Specification
An overview of the working of the module and description of its resource files. It should list the languages used to program the module/script/feature etc. It may also contain a sample output presented if it clarifies the working of the module/script/feature etc. It should contain warnings, important notes, tips etc. relevant to the working of the module/script/feature etc.

===== Operation Process
This section is relevant to modules/scripts/features etc. in which knowledge of the operation process is needed before customization can be done. Should detail the step-by-step process of the inner-working of the module/script/feature precisely. Should explain exception handling and relevant justifications.

===== Customization
This section is very important as it explains how the module can be customized in order to suit the needs of the maintainer/system administrator. Should explain the use, format and steps-to-customize of all customizable resource files. May contain recommendations and tips.

===== See Also
Some documentation pages are related to other documentation pages. This section should contain a list of links to all of them. Explanations are not necessary and generally should be avoided. The list should contain sections that should be read in continuation for better understanding.

===== References
A page may not always be completely comprehensive and may lack the back-story and discussions to sections. This section lists links to places which the user can refer to as well as places that were referred to while making the page. Proper format should be followed. Link should be properly named, followed by the origin of the resource and the creation/reference date of the resource (if applicable).

== References
. https://groups.google.com/forum/#!topic/worldnegativeone/sOfaMAHD-OI["Start of Documentation!"]. World Negative One Mailing List. 15-Jun-2014.
. https://developer.gnome.org/gdp-style-guide/stable/fundamentals-1.html.en[General Style Requirements]. GNOME-STYLE. GNOME Developer Documentation.
. https://help.ubuntu.com/community/WikiGuide/PageCreation[/PageCreation]. WikiGuide. Ubuntu Documentation.
. https://help.ubuntu.com/community/DocumentationTemplate[DocumentationTemplate]. WikiGuide. Ubuntu Documentation.
. https://groups.google.com/forum/#!topic/worldnegativeone/Eq55nPFxskY["Documentation Welcome Page"]. World Negative One Mailing List. 29-Jan-2014.
. https://groups.google.com/forum/#!topic/worldnegativeone/jQrzClndZzc["Documentation Initiated!"]. World Negative One Mailing List. 27-Jan-2014.
. https://groups.google.com/forum/#!topic/worldnegativeone/cSbL78RZDrU["Documentation Tool Development"]. World Negative One Mailing List. 25-Jan-2014. 
. https://groups.google.com/forum/#!topic/worldnegativeone/8M3keD9qDrg["VOTE - Documentation Tool"]. World Negative One Mailing List. 23-Jan-2014.
. http://en.wikipedia.org/wiki/AsciiDoc[AsciiDoc]. Wikipedia.org.
